In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
dt = pd.read_csv(r'C:\Users\REBIRTH JEREMYELEVEN\Desktop\2.01.+Admittance.csv')

In [3]:
dt.head()

SAT Admitted
0  1363       No
1  1792      Yes
2  1954      Yes
3  1653       No
4  1593       No

In [4]:
dt1 = dt.copy()

In [5]:
dt1['Admitted'] = dt1['Admitted'].map({'Yes':1, 'No': 0})

In [6]:
target = dt1['Admitted']
predictor = dt1['SAT']

In [7]:
predictor1 = sm.add_constant(predictor)
log_reg = sm.Logit(target, predictor1)
result_reg = log_reg.fit()

result_reg.summary()

C:\Users\REBIRTH JEREMYELEVEN\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


Optimization terminated successfully.
         Current function value: 0.137766
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      166
Method:                           MLE   Df Model:                            1
Date:                Sat, 18 Mar 2023   Pseudo R-squ.:                  0.7992
Time:                        19:11:46   Log-Likelihood:                -23.145
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.805e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -69.9128     15.737     -4.443      0.000    -100.756     -39.070
SAT            0.0420      0.009      4.454      0.000       0.024       0.060
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [8]:
data = pd.read_csv(r'C:\Users\REBIRTH JEREMYELEVEN\Desktop\2.02.+Binary+predictors.csv')

In [9]:
data1 = data.copy()
data1.head()

SAT Admitted  Gender
0  1363       No    Male
1  1792      Yes  Female
2  1954      Yes  Female
3  1653       No    Male
4  1593       No    Male

In [10]:
data1['Gender'] = data1['Gender'].map({'Female':1, 'Male':0})
data1['Admitted'] = data1['Admitted'].map({'Yes':1,'No':0})

In [11]:
dep_var = data1['Admitted']
indep_vars = data1[['SAT','Gender']]

In [12]:
inpv_c = sm.add_constant(indep_vars)
log_reg = sm.Logit(dep_var, inpv_c)
result = log_reg.fit()

result.summary()

Optimization terminated successfully.
         Current function value: 0.120117
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      165
Method:                           MLE   Df Model:                            2
Date:                Sat, 18 Mar 2023   Pseudo R-squ.:                  0.8249
Time:                        19:11:46   Log-Likelihood:                -20.180
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.118e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -68.3489     16.454     -4.154      0.000    -100.598     -36.100
SAT            0.0406      0.010      4.129      0.000       0.021       0.060
Gender         1.9449      0.846      2.299      0.022       0.287       3.603
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [13]:
np.set_printoptions(formatter={'float': lambda x: '{0:0.2f}'.format(x)})
result.predict()

array([0.00, 1.00, 1.00, 0.23, 0.02, 0.99, 1.00, 1.00, 1.00, 0.01, 1.00,
       1.00, 0.76, 0.00, 0.60, 1.00, 0.11, 0.12, 0.51, 1.00, 1.00, 1.00,
       0.00, 0.01, 0.97, 1.00, 0.48, 0.99, 1.00, 0.99, 0.00, 0.83, 0.25,
       1.00, 1.00, 1.00, 0.31, 1.00, 0.23, 0.00, 0.02, 0.45, 1.00, 0.00,
       0.99, 0.00, 0.99, 0.00, 0.00, 0.01, 0.00, 1.00, 0.92, 0.02, 1.00,
       0.00, 0.37, 0.98, 0.12, 1.00, 0.00, 0.78, 1.00, 1.00, 0.98, 0.00,
       0.00, 0.00, 1.00, 0.00, 0.78, 0.12, 0.00, 0.99, 1.00, 1.00, 0.00,
       0.30, 1.00, 1.00, 0.00, 1.00, 1.00, 0.85, 1.00, 1.00, 0.00, 1.00,
       1.00, 0.89, 0.83, 0.00, 0.98, 0.97, 0.00, 1.00, 1.00, 0.03, 0.99,
       0.96, 1.00, 0.00, 1.00, 0.01, 0.01, 1.00, 1.00, 1.00, 0.00, 0.00,
       0.02, 0.33, 0.00, 1.00, 0.09, 0.00, 0.97, 0.00, 0.75, 1.00, 1.00,
       0.01, 0.01, 0.00, 1.00, 0.00, 0.99, 0.57, 0.54, 0.87, 0.83, 0.00,
       1.00, 0.00, 0.00, 0.00, 1.00, 0.04, 0.00, 0.01, 1.00, 0.99, 0.52,
       1.00, 1.00, 0.05, 0.00, 0.00, 0.00, 0.68, 1.

In [14]:
result.pred_table()

array([[69.00, 5.00],
       [4.00, 90.00]])

In [15]:
cm = pd.DataFrame(result.pred_table())
cm.columns = ['Prediction0','Prediction1']
cm = cm.rename(index={0:"Actual0", 1:'Actual1'})
cm

Prediction0  Prediction1
Actual0         69.0          5.0
Actual1          4.0         90.0

In [16]:
cmr = np.array(cm)
Accuracy = (cmr[0,0]+cmr[1,1])/cmr.sum()
Accuracy

0.9464285714285714

In [17]:
d = pd.read_csv(r'C:\Users\REBIRTH JEREMYELEVEN\Desktop\2.03.+Test+dataset.csv')

In [18]:
d1 = d.copy()
d1['Admitted'] = d1['Admitted'].map({'Yes':1, 'No':0})
d1['Gender'] = d1['Gender'].map({'Female':1, 'Male':0})

In [19]:
dep_var1 = d1['Admitted']
indep_vars = d1.drop(['Admitted'],axis=1)

In [20]:
indv_c = sm.add_constant(indep_vars)

indv_c

const   SAT  Gender
0     1.0  1323       0
1     1.0  1725       1
2     1.0  1762       1
3     1.0  1777       0
4     1.0  1665       0
5     1.0  1556       1
6     1.0  1731       1
7     1.0  1809       1
8     1.0  1930       1
9     1.0  1708       0
10    1.0  1970       1
11    1.0  2039       1
12    1.0  1681       1
13    1.0  1444       0
14    1.0  1726       0
15    1.0  1876       1
16    1.0  1485       0
17    1.0  1500       1
18    1.0  1900       0

In [21]:
def confusion_matrix(dp1, actual, model):
    p_v = model.predict(dp1)
    bins = np.array([0,0.5,1])
    cm = np.histogram2d(actual, p_v, bins=bins)[0]
    accuracy = (cm[0,0] + cm[1,1])/cm.sum()
    return cm, accuracy

In [22]:
confusion_matrix(indv_c, dep_var1, result)

(array([[5.00, 1.00],
        [1.00, 12.00]]), 0.8947368421052632)